#!/usr/bin/env python3
"""
Generate tools/out/defines.lua (a real defines stub for the data-stage harness)
from a Factorio runtime-api.json dump (e.g. the one shipped in the
factorio-docs-skill GitHub repo, game 2.0.76), plus tools/out/defines_prototypes.json
(the defines.prototypes type/subtype map used by the audit).

The docs JSON carries the entry *names* of every defines namespace but not the
numeric values. Only values that data-stage code can observe are fixed here:
defines.direction gets its real, documented values (north=0 … northnorthwest=15).
Everything else only needs consistent, non-nil keys (it is used as an opaque
key/table index during the data stage), so the JSON `order` is used as a
placeholder value.

Usage:
    python3 tools/gen_defines.py --runtime-json /path/to/runtime-api.json \
        --out-dir tools/out
"""

import argparse
import json
import os

DIRECTION_VALUES = {
    "north": 0, "northeast": 1, "east": 2, "southeast": 3,
    "south": 4, "southwest": 5, "west": 6, "northwest": 7,
    "northnortheast": 8, "eastnortheast": 9, "eastsoutheast": 10,
    "southsoutheast": 11, "southsouthwest": 12, "westsouthwest": 13,
    "westnorthwest": 14, "northnorthwest": 15,
}

# Prototype types whose data-stage "defines" is a subkey map (values are arrays)
# rather than scalar constants — handled structurally by gen code below.


def lua_value(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    return '"%s"' % v.replace("\\", "\\\\").replace('"', '\\"')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--runtime-json", required=True)
    ap.add_argument("--out-dir", default=os.path.join(os.path.dirname(os.path.abspath(__file__)), "out"))
    args = ap.parse_args()

    with open(args.runtime_json) as f:
        docs = json.load(f)

    defines = {}
    prototypes_subkeys = {}
    for ns in docs.get("defines", []):
        name = ns["name"]
        entries = ns.get("values") or []
        if name == "prototypes":
            sub = ns.get("subkeys") or []
            for s in sub:
                if "name" in s:
                    prototypes_subkeys[s["name"]] = [v["name"] for v in (s.get("values") or [])]
            continue
        defines[name] = {}
        for e in entries:
            key = e["name"]
            if name == "direction" and key in DIRECTION_VALUES:
                defines[name][key] = DIRECTION_VALUES[key]
            else:
                defines[name][key] = e.get("order", 0)

    os.makedirs(args.out_dir, exist_ok=True)
    lua_path = os.path.join(args.out_dir, "defines.lua")
    with open(lua_path, "w") as f:
        f.write("-- Generated by tools/gen_defines.py from a runtime-api.json dump\n")
        f.write("-- (values for defines.direction are the real, documented ones;\n")
        f.write("--  all other values are consistent non-nil placeholders)\n")
        f.write("defines = defines or {}\n")
        for ns in sorted(defines):
            f.write("defines.%s = defines.%s or {}\n" % (ns, ns))
            for key in sorted(defines[ns]):
                f.write("defines.%s.%s = %s\n" % (ns, key, lua_value(defines[ns][key])))
        if prototypes_subkeys:
            f.write("defines.prototypes = defines.prototypes or {}\n")
            for base in sorted(prototypes_subkeys):
                subs = prototypes_subkeys[base]
                if not subs:
                    continue
                f.write("defines.prototypes[%s] = defines.prototypes[%s] or {}\n" % (lua_value(base), lua_value(base)))
                for s in sorted(subs):
                    f.write("defines.prototypes[%s][%s] = 0\n" % (lua_value(base), lua_value(s)))
    print(f"[gen_defines] wrote {lua_path} ({len(defines)} namespaces)")

    with open(os.path.join(args.out_dir, "defines_prototypes.json"), "w") as f:
        json.dump(prototypes_subkeys, f, indent=1, sort_keys=True)
    print(f"[gen_defines] wrote defines_prototypes.json ({len(prototypes_subkeys)} prototype base types)")


if __name__ == "__main__":
    main()
